name: CI - Seguridad y Calidad en Microservicios

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci-checks:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [ACL_service, alarma_service, processing_service, sensor_service]

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Python dependencies (si existen)
      if: hashFiles('${{ matrix.service }}/requirements.txt') != ''
      run: |
        pip install -r ${{ matrix.service }}/requirements.txt

    - name: Linter con flake8
      run: |
        pip install flake8
        flake8 ${{ matrix.service }} --count --select=E9,F63,F7,F82 --show-source --statistics || true

    - name: Análisis de seguridad con Bandit
      run: |
        pip install bandit
        bandit -r ${{ matrix.service }} || true

    - name: Detección de secretos con Gitleaks
      uses: gitleaks/gitleaks-action@v2
      with:
        fail: true
